
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
jmvAlphaOptions <- R6::R6Class(
    "jmvAlphaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL, ...) {

            super$initialize(
                package='psych',
                name='jmvAlpha',
                requiresData=TRUE,
                ...)
        
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
        
            self$.addOption(private$..vars)
        }),
    active = list(
        vars = function() private$..vars$value),
    private = list(
        ..vars = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
jmvAlphaResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        main = function() private$..main,
        dropped = function() private$..dropped,
        items = function() private$..items),
    private = list(
        ..main = NA,
        ..dropped = NA,
        ..items = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Alpha")
            private$..main <- jmvcore::Table$new(
                options=options,
                name="main",
                title="Alpha",
                rows=1,
                columns=list(
                    list(`name`="raw_alpha", `title`="\u03B1"),
                    list(`name`="std_alpha", `title`="Std \u03B1"),
                    list(`name`="g6", `title`="G6 (smc)"),
                    list(`name`="average_r", `title`="Average R"),
                    list(`name`="sn", `title`="S/N"),
                    list(`name`="se", `title`="SE \u03B1"),
                    list(`name`="cil", `title`="Lower", `superTitle`="95% Confidence Interval"),
                    list(`name`="ciu", `title`="Upper", `superTitle`="95% Confidence Interval")))
            private$..dropped <- jmvcore::Table$new(
                options=options,
                name="dropped",
                title="Reliability if an item is dropped",
                rows="(vars)",
                columns=list(
                    list(`name`="var", `title`="", `content`="($key)"),
                    list(`name`="raw_alpha", `title`="\u03B1"),
                    list(`name`="std_alpha", `title`="Std \u03B1"),
                    list(`name`="g6", `title`="G6 (smc)"),
                    list(`name`="average_r", `title`="Average R"),
                    list(`name`="sn", `title`="S/N")))
            private$..items <- jmvcore::Table$new(
                options=options,
                name="items",
                title="Item statistics",
                rows="(vars)",
                columns=list(
                    list(`name`="var", `title`="", `content`="($key)"),
                    list(`name`="r", `title`="r"),
                    list(`name`="rcor", `title`="r cor"),
                    list(`name`="rdrop", `title`="r drop")))
            self$add(private$..main)
            self$add(private$..dropped)
            self$add(private$..items)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
jmvAlphaBase <- R6::R6Class(
    "jmvAlphaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'psych',
                name = 'jmvAlpha',
                version = c(1,0,0),
                options = options,
                results = jmvAlphaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Alpha
#'
#' 
#' @param data .
#' @param vars .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$main} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dropped} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$items} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$main$asDF}
#'
#' \code{as.data.frame(results$main)}
#'
#' @export
jmvAlpha <- function(
    data,
    vars) {

    options <- jmvAlphaOptions$new(
        vars = vars)

    results <- jmvAlphaResults$new(
        options = options)

    analysis <- jmvAlphaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
