
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
jmvOmegaOptions <- R6::R6Class(
    "jmvOmegaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            nfactors = 3,
            n_iter = 1,
            fm = "minres",
            flip = TRUE,
            p = 0.05,
            corrMethod = "pear",
            plot = FALSE, ...) {

            super$initialize(
                package='psych',
                name='jmvOmega',
                requiresData=TRUE,
                ...)
        
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..nfactors <- jmvcore::OptionInteger$new(
                "nfactors",
                nfactors,
                default=3,
                min=1)
            private$..n_iter <- jmvcore::OptionInteger$new(
                "n_iter",
                n_iter,
                default=1,
                min=1)
            private$..fm <- jmvcore::OptionList$new(
                "fm",
                fm,
                options=list(
                    "pa",
                    "minres",
                    "ml"),
                default="minres")
            private$..flip <- jmvcore::OptionBool$new(
                "flip",
                flip,
                default=TRUE)
            private$..p <- jmvcore::OptionNumber$new(
                "p",
                p,
                min=0,
                max=1,
                default=0.05)
            private$..corrMethod <- jmvcore::OptionList$new(
                "corrMethod",
                corrMethod,
                options=list(
                    "pear",
                    "poly"),
                default="pear")
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=FALSE)
        
            self$.addOption(private$..vars)
            self$.addOption(private$..nfactors)
            self$.addOption(private$..n_iter)
            self$.addOption(private$..fm)
            self$.addOption(private$..flip)
            self$.addOption(private$..p)
            self$.addOption(private$..corrMethod)
            self$.addOption(private$..plot)
        }),
    active = list(
        vars = function() private$..vars$value,
        nfactors = function() private$..nfactors$value,
        n_iter = function() private$..n_iter$value,
        fm = function() private$..fm$value,
        flip = function() private$..flip$value,
        p = function() private$..p$value,
        corrMethod = function() private$..corrMethod$value,
        plot = function() private$..plot$value),
    private = list(
        ..vars = NA,
        ..nfactors = NA,
        ..n_iter = NA,
        ..fm = NA,
        ..flip = NA,
        ..p = NA,
        ..corrMethod = NA,
        ..plot = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
jmvOmegaResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        omega = function() private$..omega,
        plot = function() private$..plot),
    private = list(
        ..omega = NA,
        ..plot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Omega")
            private$..omega <- jmvcore::Preformatted$new(
                options=options,
                name="omega",
                title="Omega Estimates")
            private$..plot <- jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot",
                visible="(plot)",
                width=400,
                height=300,
                renderFun=".plot")
            self$add(private$..omega)
            self$add(private$..plot)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
jmvOmegaBase <- R6::R6Class(
    "jmvOmegaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'psych',
                name = 'jmvOmega',
                version = c(1,0,0),
                options = options,
                results = jmvOmegaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Omega
#'
#' 
#' @param data .
#' @param vars .
#' @param nfactors .
#' @param n_iter .
#' @param fm .
#' @param flip .
#' @param p .
#' @param corrMethod .
#' @param plot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$omega} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
jmvOmega <- function(
    data,
    vars,
    nfactors = 3,
    n_iter = 1,
    fm = "minres",
    flip = TRUE,
    p = 0.05,
    corrMethod = "pear",
    plot = FALSE) {

    options <- jmvOmegaOptions$new(
        vars = vars,
        nfactors = nfactors,
        n_iter = n_iter,
        fm = fm,
        flip = flip,
        p = p,
        corrMethod = corrMethod,
        plot = plot)

    results <- jmvOmegaResults$new(
        options = options)

    analysis <- jmvOmegaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
